DROP TABLE IF EXISTS LIBRO_AUTOR;

DROP TABLE IF EXISTS AUTORES;

DROP TABLE IF EXISTS LIBROS;

CREATE TABLE AUTORES (
	AUTOR_NOMBRE VARCHAR(50) NOT NULL,
	AUTOR_ID SERIAL PRIMARY KEY
);

CREATE TABLE LIBROS (
	LIBRO_ID SERIAL PRIMARY KEY,
	LIBRO_NOMBRE VARCHAR(50) NOT NULL,
	LIBRO_FECHA_PUBLICACION DATE NOT NULL
);

CREATE TABLE LIBRO_AUTOR (
	LIBRO_AUTOR_ID SERIAL PRIMARY KEY,
	LIBRO_ID INT REFERENCES LIBROS (LIBRO_ID),
	AUTOR_ID INT REFERENCES AUTORES (AUTOR_ID)
);

INSERT INTO
	AUTORES (AUTOR_NOMBRE)
VALUES
	('Gabriel García Márquez'),
	('Isabel Allende'),
	('Mario Vargas Llosa'),
	('Jorge Luis Borges'),
	('Julio Cortázar');

INSERT INTO
	LIBROS (LIBRO_NOMBRE, LIBRO_FECHA_PUBLICACION)
VALUES
	('Cien años de soledad', '1967-05-30'),
	('La casa de los espíritus', '1982-10-12'),
	('La ciudad y los perros', '1963-01-01'),
	('El Aleph', '1949-09-22'),
	('Rayuela', '1963-02-18'),
	('Crónica de una muerte anunciada', '1981-03-15'),
	('La fiesta del chivo', '2000-06-01'),
	('Ficciones', '1944-10-15'),
	('Cuentos completos', '1994-11-11');

INSERT INTO
	LIBRO_AUTOR (LIBRO_ID, AUTOR_ID)
VALUES
	(1, 1),
	(2, 2),
	(3, 3),
	(4, 4),
	(5, 5),
	(6, 1),
	(7, 3),
	(8, 4),
	(9, 5);

DELETE FROM LIBRO_AUTOR
WHERE
	LIBRO_AUTOR_ID IN (27, 26, 25);

SELECT
	*
FROM
	LIBROS;

SELECT
	L.LIBRO_NOMBRE AS "NOMBRE DEL LIBRO",
	A.AUTOR_NOMBRE AS "NOMBRE DEL AUTOR"
FROM
	LIBROS L
	JOIN LIBRO_AUTOR LA ON L.LIBRO_ID = LA.LIBRO_ID
	JOIN AUTORES A ON A.AUTOR_ID = LA.AUTOR_ID;

SELECT
	A.AUTOR_NOMBRE AS "NOMBRE AUTOR",
	L.LIBRO_NOMBRE AS "NOMBRE DEL LIBRO",
	L.LIBRO_FECHA_PUBLICACION AS "FECHA DE PUBLICACION"
FROM
	LIBROS L
	JOIN LIBRO_AUTOR LA ON L.LIBRO_ID = LA.LIBRO_ID
	JOIN AUTORES A ON A.AUTOR_ID = LA.AUTOR_ID
WHERE
	A.AUTOR_ID = 5;

SELECT
	COUNT(*) AS "Total de libros"
FROM
	LIBROS;

SELECT
	A.AUTOR_NOMBRE AS "NOMBRE DEL AUTOR",
	L.LIBRO_NOMBRE AS "NOMBRE DEL LIBRO",
	L.LIBRO_FECHA_PUBLICACION AS "FECHA DE PUBLICACION"
FROM
	AUTORES A
	JOIN LIBRO_AUTOR LA ON LA.AUTOR_ID = A.AUTOR_ID
	JOIN LIBROS L ON L.LIBRO_ID = LA.LIBRO_ID
WHERE L.LIBRO_NOMBRE = 'Cien años de soledad'